os: windows
language: shell

notifications:
  email: false

install:
  - choco install -y nuget.commandline vswhere
  - nuget sources add -Name nuget.org -Source https://api.nuget.org/v3/index.json || true
  - nuget restore uploader/uploader.sln -Source https://api.nuget.org/v3/index.json

script:
  - export MSBUILD_PATH=$(vswhere -latest -requires Microsoft.Component.MSBuild -find MSBuild/**/Bin/MSBuild.exe | head -n 1)
  - '"$MSBUILD_PATH" uploader/uploader.sln /p:Configuration=Release /p:Platform=x64 /m'
  - '"$MSBUILD_PATH" uploader/uploader.sln /p:Configuration=Debug /p:Platform=x64 /m'
