<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>uploader.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MSTest" Version="3.2.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\uploader\LocalizationHelper.cs" Link="Source\LocalizationHelper.cs" />
    <Compile Include="..\uploader\LocalizationBase.cs" Link="Source\LocalizationBase.cs" />
    <Compile Include="..\uploader\Settings.cs" Link="Source\Settings.cs" />
  </ItemGroup>

</Project>
