<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../uploader/uploader/UploadForm.cs" />
    <Compile Include="../uploader/uploader/MainForm.cs" />
    <Compile Include="../uploader/uploader/Settings.cs" />
    <Compile Include="../uploader/uploader/Utils.cs" />
    <Compile Include="../uploader/uploader/LocalizationHelper.cs" />
    <Compile Include="../uploader/uploader/LocalizationBase.cs" />
    <PackageReference Include="RestSharp" Version="112.1.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>
</Project>
